var x;
        console.log(x);
        x = 1;
        console.log("Hello");
        console.log("World");
        //alert("Hello Wold");
        x = 5.25;
        console.log(x);
        x = 'He\'\ll\'o\nWorld';
        console.log(x);
        x = true;
        console.log(x);
        x = false;
        console.log(x);
        x = null;
        console.log(x);